### PR TITLE
Speed Up our rituals, iesnium and eldritch upgrades and otherthings

### LINKED ISSUE #1266: Possessed Warden hitbox is notably larger than it should be
**Describe the bug**
The Possessed Warden hitbox is absolutely massive, roughly triple the size of the model

**To Reproduce**
1. Spawn Possessed Warden
2. F3 + B to enable hitboxes
3. Look at Possessed Warden

**Expected behavior**
Not a nearly 6 block tall hitbox.

**Screenshots**
The code that is causing the problem (Line 128, `OccultismEntities.java`):
image
Normal Warden hitbox size:
image
Possessed Warden hitbox size:
image

**System (please complete the following information):**
- Occultism Version: 1.169.0
- OS: Windows 10
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: [Craftoria](https://www.curseforge.com/minecraft/modpacks/craftoria) 1.9.0

**Additional context**

### LINKED ISSUE #1272: Osorin's Unbound Calling has incorrect name on Wild Horde Drowned ritual page
**Describe the bug**
See title.

**To Reproduce**
Open guide book, spam "unlock visible entries" button, look at Wild Horde Drowned page, hover over linked ritual and view tool tip (or click on it and check the title of the page you're directed to).

**Expected behavior**
All names should be in agreement.

**System (please complete the following information):**
- Occultism Version: 1.169.0
- OS: Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: FTB Evolution + alltheleaks

### PR DESCRIPTION
**Pull request by Eqis-Edu**
# Sacrificial Bowls

### Copper/Silver Sacrificial Bowl
+ Decorative, works like a sacrificial bowl
+ Craftable with a sacrificial bowl and an ingot

### Iesnium Sacrificial Bowl
+ Works like a golden sacrificial bowl, but 4x faster
+ Afrit tier craft (golden bowl, iesnium block, spirit crystal, afrit essence, research dust)

### Eldritch Chalice
(not really a bowl...)
+ Works like a golden sacrificial bowl, but makes the recipe instantly
+ Last tier craft (almost the old recipe of reinforced deepslate)
+ The (useful) trophy item 

### Pentacles
Accepts the Iesnium sacrificial bowl and the Eldritch Chalice in the middle, but the preview only shows the golden sacrificial bowl to avoid spoilers

### Ritual Duration
Due to the new methods to speed up rituals, the entire ritual duration has been revised, now follows a formula based on type and tier (and reordered in the datagen file)
+ Summon: 60 x tier (half for time/weather jobs)
+ Possess: 30 x tier (half to random)
+ Familiar: 45 x tier
+ Craft: 30 x tier^2 + 30 
+ Resurrect: 15 familiar, 30 allay
+ Repair: 5 chalk, 60 others
+ Wild: 90 mob (half to random), 180 item

# Pedestals

### Otherstone pedestal
+ Same hitbox as storage actuator

### Silver pedestal
+ Decorative
+ Craft with other stone pedestal and silver ingot

### Storage actuator base
+ Change to use copper in recipe and texture
+ Same hitbox as storage actuator

### Stabilized storage actuator
+ Storage actuator with built-in 7x level 4 stabilizer (the amount is configurable)
+ Last tier craft (items corresponding to the setup and three echo dust)

### Stabilizer level 0
+ Crafting material, to craft level 1 instead of pedestal
+ Decorative
+ Craft with other stone pedestal

# Iesnium Anvil
+ Better Anvil
+ Indestructible
+ Reduced cost
+ Slower cost increase
+ Higher max level cost
+ Can exceeds max enchantment level by 1
+ Marid tier craft (anvil, 3x iesnium block, marid essence)

# Otherglass
+ Invisible block, see with third eye
+ Shapped craft (4x iesnium nugget, 4x endstone dust, and glass)

# Otherflower
+ Natural version generate in Grove
+ Craft with any Flower on spirit fire
+ Clone any dye, otherflower + dye (tag) -> 3 dye (vanilla)
+ Suspicius stews give third eye
+ Can be placed in flower pot

# Iesnium Golem
+ Stronger iron golem
+ Invulnerable except to crouching player (one hit to dismiss, drops soul fragment)
+ Marid tier possess (3x iesnium block, marid essence, spirit crystal, nether star, sacrifice iron golem)

# Rainbow and Void Chalks
+ Rainbow is for non foundation chalks, void is for all
+ Both eldritch tier
+ Can replace any glyph, but you choose the color using any dye
+ Can be used as brush (crouching)
+ Toggleable random color auto changing (flickering)

### Pentacles
Accepts rainbow or void glyphs in any valid position, but the preview only shows default colored version to avoid confusion

# Trinity gem
+ Upgraded Soul Gem
+ Separated blacklist entity (default empty, but ender dragon still uncatchable)
+ Last tier craft

# Others
+ Easier reinforced deepslate recipe, low tier (wild) and cost (to 4x obsians, 4x iron bars, 1 deepslate, still needing warden sacrifice)
+ Reinforced deepslate will drop if mined with infused/iesnium pickaxe
+ Silver ore need iron tool (to match other mods that add silver)
+ Iesnium height changed, found in all nether y 0 ~ 128 (from 50 ~ -64, to match nether depth)
+ Fix djinni hat not moving with head (when pushing or hitting djinni)
+ Time and weather spirits work faster (reduced default max age)
+ Random special animals use wind charge instead firework, because using firework in a block don't work
+ Text "foil" to "glint" (match with visual settings)
+ Soul shard reset the fall distance and effects (to familiars don't get stuck in infinite death loop)
+ Books of binding (unbound) stack up 16
+ Guardian familiar fixes drop (only one soul shard instead two)
+ Guardian in ring no more grant infinity immortality (now auto-leaves the ring to does its normal function, limited uses)
+ Recipes for bee nest and bell (wild tier)
+ fix #1266 
+ Dimensional mineshaft has redstone interactions (signal turn off, comparator can read lamp durability and occupied slots) 
+ Coal crushing (missing recipe, discord report)
+ Tallow block (9 tallow), infinity burn (like netherhack), small speed and jump reduction when stand on top
+ Removed various warnings
+ Familiar goat gets random name when separated from chimera (shub niggurath keep this name after transform)
+ fix #1272 

# Image

(yeah, some blocks already exist, but I put to see all variations)

https://github.com/user-attachments/assets/7de61a7d-9bbc-44e4-a0d4-16fcd19f0411
Flickering glyphs (rainbow and void), the pentacle still working

### CODE REVIEW

**Comment by klikli-dev** [comment]
@Eqis-Edu as always, fanstastic content!
Question about the stabilized actuator, does crafting keep the contained items?

File: src/main/java/com/klikli_dev/occultism/common/entity/familiar/IesniumGolemEntity.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+        this.setHealth(this.getMaxHealth()); //simulate a healthy familiar to avoid death on respawn
+
+        var entityData = new CompoundTag();
+        var id = this.getEncodeId();
+        if (id != null)
+            entityData.putString("id", id);
+        entityData = this.saveWithoutId(entityData);
+
+        shard.set(DataComponents.ENTITY_DATA, CustomData.of(entityData));
+        this.setHealth(health);
```
Comment (orochi02) [inline src/main/java/com/klikli_dev/occultism/common/entity/familiar/IesniumGolemEntity.java:109]: wasnt his health set in l98 already?

File: src/main/java/com/klikli_dev/occultism/datagen/book/familiar_rituals/IesniumGolemEntry.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+
+        this.page("description", () -> BookTextPageModel.create()
+                .withTitle(this.context().pageTitle())
+                .withText(this.context().pageText())
+        );
+        this.pageTitle("Iesnium Golem");
+        this.pageText("""
+                An Iesnium Golem is a direct upgrade from a regular Iron Golem, this new version is much stronger and invulnerable. \\
+                Only a player can dismiss them, by hitting while is crouched, returning the {0}.
```
Comment (orochi02) [inline src/main/java/com/klikli_dev/occultism/datagen/book/familiar_rituals/IesniumGolemEntry.java]:
```suggestion
                Only a player can dismiss them, by hitting while crouched, returning the {0}.
```

**Comment by orochi02** [comment]
i understand that otherglass is a bit special in that it is invisible compared to other (other-)items like otherstone and otherwood but do we really need to use iesnium (nuggets) and endstone (dust)? if throwing glass in spiritfire is a bit too.. much? how about acquiring it through a trader that you have to summon also like otherstone?

if yall think the recipe cost is justified then ignore my comment

File: src/main/resources/data/minecraft/loot_table/blocks/reinforced_deepslate.json [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+        {
+          "type": "minecraft:item",
+          "name": "minecraft:reinforced_deepslate",
+          "conditions": [
+            {
+              "condition": "minecraft:match_tool",
+              "predicate": {
+                "items": [
+                  "occultism:infused_pickaxe",
+                  "occultism:iesnium_pickaxe"
```
Comment (orochi02) [inline src/main/resources/data/minecraft/loot_table/blocks/reinforced_deepslate.json:16]: i **highly** suggest documenting this somewhere in the dict of spirits

**Review by orochi02 — COMMENTED** [review]
eh not used to modded mc so please be merciful w me

**Comment by Eqis-Edu** [comment]
> Question about the stabilized actuator, does crafting keep the contained items?

The recipe use a new base and matrix, not the actuator (because it does not copy the items inside)

File: src/main/java/com/klikli_dev/occultism/common/entity/familiar/IesniumGolemEntity.java (hunk 1 above)
Comment (Eqis-Edu) [reply src/main/java/com/klikli_dev/occultism/common/entity/familiar/IesniumGolemEntity.java:109]: this changes the life inside the soul shard when dropped, since the copy as 0 health

File: src/main/resources/data/minecraft/loot_table/blocks/reinforced_deepslate.json (hunk 3 above)
Comment (Eqis-Edu) [reply src/main/resources/data/minecraft/loot_table/blocks/reinforced_deepslate.json:16]: It's already there, under the recipe

Comment (Eqis-Edu) [reply src/main/resources/data/minecraft/loot_table/blocks/reinforced_deepslate.json:16]: added under description

File: src/main/java/com/klikli_dev/occultism/registry/OccultismItems.java [hunk 4]
```diff
@@ -91,21 +91,21 @@ public class OccultismItems {
...
             "book_of_binding_bound_djinni", () -> new BookOfBindingBoundItem(defaultProperties().stacksTo(1).component(OccultismDataComponents.SPIRIT_NAME, TextUtil.SPIRIT_NAME_NOT_YET_KNOWN)));
     public static final DeferredItem<BookOfBindingItem> BOOK_OF_BINDING_AFRIT = ITEMS.register(
-            "book_of_binding_afrit", () -> new BookOfBindingItem(defaultProperties().stacksTo(1)));
+            "book_of_binding_afrit", () -> new BookOfBindingItem(defaultProperties().stacksTo(16)));
     public static final DeferredItem<BookOfBindingBoundItem> BOOK_OF_BINDING_BOUND_AFRIT = ITEMS.register(
             "book_of_binding_bound_afrit", () -> new BookOfBindingBoundItem(defaultProperties().stacksTo(1).component(OccultismDataComponents.SPIRIT_NAME, TextUtil.SPIRIT_NAME_NOT_YET_KNOWN)));
     public static final DeferredItem<BookOfBindingItem> BOOK_OF_BINDING_MARID = ITEMS.register(
-            "book_of_binding_marid", () -> new BookOfBindingItem(defaultProperties().stacksTo(1)));
+            "book_of_binding_marid", () -> new BookOfBindingItem(defaultProperties().stacksTo(16)));
```
Comment (orochi02) [inline src/main/java/com/klikli_dev/occultism/registry/OccultismItems.java:110]: love these, awesome QOL changes

**Review by orochi02 — APPROVED** [review]
take my approval w a grain of salt

File: src/main/java/com/klikli_dev/occultism/datagen/book/binding_rituals/TrinityGemEntry.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    protected void generatePages() {
+        this.page("spotlight", () -> BookSpotlightPageModel.create()
+                .withItem(Ingredient.of(OccultismItems.TRINITY_GEM_ITEM))
+                .withText(this.context().pageText()));
+        this.pageText("""
+                        Forging the [](item://occultism:trinity_gem) is a service provided by an {0}.
+                        This gem is upgraded version of [](item://occultism:soul_gem) created with
+                        3 distinct essences, 3 powerful dusts and 3 iesnium dusts.
+                        The trinity gem has a smaller entity blacklist (none by default), but some mobs can still
+                        incompatible as the ender dragon.
```
Comment (orochi02) [inline src/main/java/com/klikli_dev/occultism/datagen/book/binding_rituals/TrinityGemEntry.java]:
```suggestion
                        The trinity gem has a smaller entity blacklist (none by default), but some mobs might still be
                        incompatible like the ender dragon.
```

**Comment by orochi02** [comment]
this morning after i woke up i had a thought: the stabilized storage actuator is really really nice but.. cant it be used like a shulker box? is having players taking a whole giant storage solution as a replacement backpack/shulker box really desirable?

**Comment by Eqis-Edu** [comment]
> this morning after i woke up i had a thought: the stabilized storage actuator is really really nice but.. cant it be used like a shulker box? is having players taking a whole giant storage solution as a replacement backpack/shulker box really desirable?

Players can already do this with the normal actuator (taking a few blocks and the stabilizers can quickly setup to enable placing items), but it's much simpler to just use the accessor (with the actuator in a loaded chunk, at world spawn or with another mod).

**Comment by Eqis-Edu** [comment]
@klikli-dev this PR is ready

**Comment by klikli-dev** [comment]
Sorry I completely missed the ping (had a flood of other github mails in my inbox). Will look into this today!
